### ISSUE TITLE
Record versioning metadata in output

### ISSUE THREAD

**Issue by erictzeng** [shelhamer/ale-record#3]
It's an almost absolute certainty that the format of recordings is going to change at some point in the future, so we may as well make our lives a little easier from the get-go and record versioning metadata in the output. This could be as simple as an integer that increments every time the format changes.

This also raises the question of whether or not we would like to maintain backwards compatibility. We could also just check out older versions whenever we need to read older recordings.

**Comment by shelhamer** [comment]
> It's an almost absolute certainty that the format of recordings is going to change at some point in the future

What defeatism, and at such a young age. You're completely right. We should save a version.

> This could be as simple as an integer that increments every time the format changes

As long as we remember to increment it. I'm not sure whether I like this more or less than saving the current git commit. The number tells you whether you're in the past or future at a glance, but either way one has to inspect history to really know the format.

> Whether or not we would like to maintain backwards compatibility

I worry this could be an unnecessary struggle, but we'll see what we end up needing.

**Comment by shelhamer** [comment]
`subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).strip()` returns the git commit.

**Comment by erictzeng** [comment]
I'm not a fan of using the git commit hash—it would take too much effort to determine the format something was saved in. If I told you I had one recording from `b899f8497067daab7e5e688814787ea3cfa179a4` and one recording from `ab271680a2b1f6273d32ac696b6706547807009d`, are these recordings stored in the same format? (I believe the answer is yes, here.)

That being said, _additionally_ including the git commit if it is available sounds like it could be a good idea. But I'd rather rely primarily on a manually incremented version number, especially since it's not a guarantee that the git commit hash will always be available (e.g. some strange world where someone actually wants to deploy this code base).

**Comment by shelhamer** [comment]
Ok, I'm convinced that we should record a version number that we maintain
ourselves. I'll send a PR today unless you do it first.

**Comment by shelhamer** [comment]
Resolved by #4.
